config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'movies/home'
  get 'movies', to: 'movies#index', as: :movies
  get 'movies/:id', to: 'movies#show', as: :movie
  get 'lists/home'
  get 'lists', to: 'lists#index'
  get 'lists/new', to: 'lists#new'
  post 'lists', to: 'lists#create'
  get 'lists/:id', to: 'lists#show', as: :list
  get 'bookmarks/home'
  get 'lists/:list_id/bookmarks/new', to: 'bookmarks#new', as: :new_list_bookmark
  post 'lists/:list_id/bookmarks', to: 'bookmarks#create', as: :list_bookmarks
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates :list_id, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def home
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]


  def home
  end

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show]

  def home
  end

  def index
    @movies = Movie.all
  end

  def show
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/home.html.erb
<h1>Bookmarks#home</h1>
<p>Find me in app/views/bookmarks/home.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<p>for <%= @list.name %></p>

<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
<% end %>


<p><%= link_to 'List', lists_path %></p>
<p><%= link_to @list.name, list_path(@list) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/home.html.erb
<h1>Lists#home</h1>
<p>Find me in app/views/lists/home.html.erb</p>

app/views/lists/index.html.erb
<h1>List<h1>

  <% @lists.each do |list| %>
    <p><%= link_to list.name, list %></p>
  <% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render "form", list: @list %>

app/views/lists/show.html.erb
<h1>Show<h1>

<h2><%= @list.name %></h2>

<ul class="list-group">
  <% @list.bookmarks.each do |bookmark| %>
    <li class="list-group-item"><%= bookmark.comment %><%= link_to "Remove",
                  bookmark_path(bookmark),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>

<p><%= link_to 'Leave a bookmark', new_list_bookmark_path(@list) %></p>
<p><%= link_to 'Listes', lists_path %></p>

app/views/movies/home.html.erb
<h1>Movies#home</h1>
<p>Find me in app/views/movies/home.html.erb</p>

app/views/movies/index.html.erb
<h1>Movies<h1>

  <% @movies.each do |movie| %>
    <p><%= link_to movie.title, movie %></p>
  <% end %>

app/views/movies/show.html.erb
<h1>Show<h1>

<h2><%= @movie.title %></h2>

<ul class="list-group">
  <% @movie.bookmarks.each do |movie| %>
    <li class="list-group-item"><%= bookmark.comment %></li>
  <% end %>
</ul>

<p><%= link_to 'Leave a bookmark', new_movie_bookmark_path(@movie) %></p>
<p><%= link_to 'Movies', movies_path %></p>